name: Deploy to EC2

on:
  push:
    branches:
      
main
pull_request:
  branches:
main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      
name: Checkout Repository
      uses: actions/checkout@v4

      
name: Update Packages
      run: sudo apt-get update -y

      
name: Install SSH Client
      run: sudo apt-get install -y openssh-client

      
name: Setup SSH Key
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" | base64 --decode > $HOME/.ssh/id_rsa
        chmod 600 $HOME/.ssh/id_rsa
        ssh-keyscan -H "$SSH_HOST" >> $HOME/.ssh/known_hosts
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SSH_HOST: ${{ secrets.SSH_HOST }}

      
name: Deploy to EC2
      run: |
        ssh $SSH_USER@$SSH_HOST "cd $WORK_DIR && git pull origin $MAIN_BRANCH"
      env:
        SSH_USER: ${{ secrets.SSH_USER }}
        SSH_HOST: ${{ secrets.SSH_HOST }}
        WORK_DIR: ${{ secrets.WORK_DIR }}
        MAIN_BRANCH: ${{ secrets.MAIN_BRANCH }}

      
name: Cleanup SSH Key
      run: rm -rf $HOME/.ssh